<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AFG'],
            ['name' => 'Albania', 'code' => 'ALB'],
            ['name' => 'Algeria', 'code' => 'DZA'],
            ['name' => 'Andorra', 'code' => 'AND'],
            ['name' => 'Angola', 'code' => 'AGO'],
            ['name' => 'Argentina', 'code' => 'ARG'],
            ['name' => 'Armenia', 'code' => 'ARM'],
            ['name' => 'Australia', 'code' => 'AUS'],
            ['name' => 'Austria', 'code' => 'AUT'],
            ['name' => 'Azerbaijan', 'code' => 'AZE'],
            ['name' => 'Bahamas', 'code' => 'BHS'],
            ['name' => 'Bahrain', 'code' => 'BHR'],
            ['name' => 'Bangladesh', 'code' => 'BGD'],
            ['name' => 'Belarus', 'code' => 'BLR'],
            ['name' => 'Belgium', 'code' => 'BEL'],
            ['name' => 'Belize', 'code' => 'BLZ'],
            ['name' => 'Benin', 'code' => 'BEN'],
            ['name' => 'Bhutan', 'code' => 'BTN'],
            ['name' => 'Bolivia', 'code' => 'BOL'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BIH'],
            ['name' => 'Botswana', 'code' => 'BWA'],
            ['name' => 'Brazil', 'code' => 'BRA'],
            ['name' => 'Bulgaria', 'code' => 'BGR'],
            ['name' => 'Burkina Faso', 'code' => 'BFA'],
            ['name' => 'Cambodia', 'code' => 'KHM'],
            ['name' => 'Cameroon', 'code' => 'CMR'],
            ['name' => 'Canada', 'code' => 'CAN'],
            ['name' => 'Chile', 'code' => 'CHL'],
            ['name' => 'China', 'code' => 'CHN'],
            ['name' => 'Colombia', 'code' => 'COL'],
            ['name' => 'Costa Rica', 'code' => 'CRI'],
            ['name' => 'Croatia', 'code' => 'HRV'],
            ['name' => 'Cuba', 'code' => 'CUB'],
            ['name' => 'Cyprus', 'code' => 'CYP'],
            ['name' => 'Czech Republic', 'code' => 'CZE'],
            ['name' => 'Denmark', 'code' => 'DNK'],
            ['name' => 'Dominican Republic', 'code' => 'DOM'],
            ['name' => 'Ecuador', 'code' => 'ECU'],
            ['name' => 'Egypt', 'code' => 'EGY'],
            ['name' => 'Estonia', 'code' => 'EST'],
            ['name' => 'Finland', 'code' => 'FIN'],
            ['name' => 'France', 'code' => 'FRA'],
            ['name' => 'Georgia', 'code' => 'GEO'],
            ['name' => 'Germany', 'code' => 'DEU'],
            ['name' => 'Greece', 'code' => 'GRC'],
            ['name' => 'Hungary', 'code' => 'HUN'],
            ['name' => 'Iceland', 'code' => 'ISL'],
            ['name' => 'India', 'code' => 'IND'],
            ['name' => 'Indonesia', 'code' => 'IDN'],
            ['name' => 'Iran', 'code' => 'IRN'],
            ['name' => 'Iraq', 'code' => 'IRQ'],
            ['name' => 'Ireland', 'code' => 'IRL'],
            ['name' => 'Israel', 'code' => 'ISR'],
            ['name' => 'Italy', 'code' => 'ITA'],
            ['name' => 'Japan', 'code' => 'JPN'],
            ['name' => 'Jordan', 'code' => 'JOR'],
            ['name' => 'Kazakhstan', 'code' => 'KAZ'],
            ['name' => 'Kyrgyzstan', 'code' => 'KGZ'],
            ['name' => 'Latvia', 'code' => 'LVA'],
            ['name' => 'Lithuania', 'code' => 'LTU'],
            ['name' => 'Luxembourg', 'code' => 'LUX'],
            ['name' => 'Malaysia', 'code' => 'MYS'],
            ['name' => 'Mexico', 'code' => 'MEX'],
            ['name' => 'Moldova', 'code' => 'MDA'],
            ['name' => 'Mongolia', 'code' => 'MNG'],
            ['name' => 'Montenegro', 'code' => 'MNE'],
            ['name' => 'Morocco', 'code' => 'MAR'],
            ['name' => 'Nepal', 'code' => 'NPL'],
            ['name' => 'Netherlands', 'code' => 'NLD'],
            ['name' => 'New Zealand', 'code' => 'NZL'],
            ['name' => 'Nigeria', 'code' => 'NGA'],
            ['name' => 'North Macedonia', 'code' => 'MKD'],
            ['name' => 'Norway', 'code' => 'NOR'],
            ['name' => 'Pakistan', 'code' => 'PAK'],
            ['name' => 'Paraguay', 'code' => 'PRY'],
            ['name' => 'Peru', 'code' => 'PER'],
            ['name' => 'Philippines', 'code' => 'PHL'],
            ['name' => 'Poland', 'code' => 'POL'],
            ['name' => 'Portugal', 'code' => 'PRT'],
            ['name' => 'Qatar', 'code' => 'QAT'],
            ['name' => 'Romania', 'code' => 'ROU'],
            ['name' => 'Russia', 'code' => 'RUS'],
            ['name' => 'Saudi Arabia', 'code' => 'SAU'],
            ['name' => 'Serbia', 'code' => 'SRB'],
            ['name' => 'Singapore', 'code' => 'SGP'],
            ['name' => 'Slovakia', 'code' => 'SVK'],
            ['name' => 'Slovenia', 'code' => 'SVN'],
            ['name' => 'South Africa', 'code' => 'ZAF'],
            ['name' => 'South Korea', 'code' => 'KOR'],
            ['name' => 'Spain', 'code' => 'ESP'],
            ['name' => 'Sri Lanka', 'code' => 'LKA'],
            ['name' => 'Sweden', 'code' => 'SWE'],
            ['name' => 'Switzerland', 'code' => 'CHE'],
            ['name' => 'Syria', 'code' => 'SYR'],
            ['name' => 'Tajikistan', 'code' => 'TJK'],
            ['name' => 'Thailand', 'code' => 'THA'],
            ['name' => 'Turkey', 'code' => 'TUR'],
            ['name' => 'Turkmenistan', 'code' => 'TKM'],
            ['name' => 'Ukraine', 'code' => 'UKR'],
            ['name' => 'United Arab Emirates', 'code' => 'ARE'],
            ['name' => 'United Kingdom', 'code' => 'GBR'],
            ['name' => 'United States', 'code' => 'USA'],
            ['name' => 'Uzbekistan', 'code' => 'UZB'],
            ['name' => 'Vietnam', 'code' => 'VNM'],
        ];

        DB::table('countries')->insert($countries);
    }
}
